# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."dash-dash" = {
    image = "mauricenino/dashdot:latest";
    volumes = [
      "/:/mnt/host:ro"
    ];
    ports = [
      "3002:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dash"
      "--network=dash_default"
      "--privileged"
    ];
  };
  systemd.services."docker-dash-dash" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dash_default.service"
    ];
    requires = [
      "docker-network-dash_default.service"
    ];
    partOf = [
      "docker-compose-dash-root.target"
    ];
    wantedBy = [
      "docker-compose-dash-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-dash_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f dash_default";
    };
    script = ''
      docker network inspect dash_default || docker network create dash_default
    '';
    partOf = [ "docker-compose-dash-root.target" ];
    wantedBy = [ "docker-compose-dash-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-dash-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
