# Auto-generated using compose2nix v0.2.1-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."gonic-gonic" = {
    image = "sentriz/gonic:latest";
    volumes = [
      "/data/Media/music/:/music:ro"
      "/data/gonic/cache/:/cache:rw"
      "/data/gonic/data/:/data:rw"
      "/data/gonic/playlists/:/playlists:rw"
      "/data/gonic/podcast/:/podcasts:rw"
    ];
    ports = [
      "4747:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gonic"
      "--network=gonic_default"
    ];
  };
  systemd.services."docker-gonic-gonic" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "no";
    };
    after = [
      "docker-network-gonic_default.service"
    ];
    requires = [
      "docker-network-gonic_default.service"
    ];
    partOf = [
      "docker-compose-gonic-root.target"
    ];
    wantedBy = [
      "docker-compose-gonic-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-gonic_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f gonic_default";
    };
    script = ''
      docker network inspect gonic_default || docker network create gonic_default
    '';
    partOf = [ "docker-compose-gonic-root.target" ];
    wantedBy = [ "docker-compose-gonic-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-gonic-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
