# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."homarr" = {
    image = "ghcr.io/homarr-labs/homarr:latest";
    environment = {
      "SECRET_ENCRYPTION_KEY" = "1bc23494dc4da156d0cfc2f0af698f77c88385ba9a07972b25b5244a1ce65f46";
    };
    volumes = [
      "/pool/data/Services/homarr/appdata:/appdata:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "7575:7575/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homarr"
      "--network=homarr_default"
    ];
  };
  systemd.services."docker-homarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-homarr_default.service"
    ];
    requires = [
      "docker-network-homarr_default.service"
    ];
    partOf = [
      "docker-compose-homarr-root.target"
    ];
    wantedBy = [
      "docker-compose-homarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-homarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homarr_default";
    };
    script = ''
      docker network inspect homarr_default || docker network create homarr_default
    '';
    partOf = [ "docker-compose-homarr-root.target" ];
    wantedBy = [ "docker-compose-homarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
