# Auto-generated using compose2nix v0.2.1-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."joplin-app" = {
    image = "joplin/server:latest";
    environmentFiles = [
      "/run/agenix/joplin-env"
    ];
    dependsOn = [
      "joplin-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:127.0.0.1"
      "--network=host"
    ];
  };
  systemd.services."docker-joplin-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    partOf = [
      "docker-compose-joplin-root.target"
    ];
    wantedBy = [
      "docker-compose-joplin-root.target"
    ];
  };
  virtualisation.oci-containers.containers."joplin-db" = {
    image = "postgres:16";
    environmentFiles = [
      "/run/agenix/joplin-env"
    ];
    volumes = [
      "/data/joplin/postgresql/:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-joplin-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    partOf = [
      "docker-compose-joplin-root.target"
    ];
    wantedBy = [
      "docker-compose-joplin-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-joplin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
